[phases.setup]
nixPkgs = ["firefox", "wget", "unzip"]

[phases.install]
cmds = [
  "chmod +x railway_setup.sh",
  "./railway_setup.sh",
  "pip install -r requirements.txt"
]

[start]
cmd = "python working_app.py"
