# Streamlit secrets configuration
# This file contains configuration for the CAGR API Monitor
# For local development, use localhost:8000
# For Streamlit Cloud deployment, update API_BASE_URL to your deployed FastAPI URL

[api]
API_BASE_URL = "http://localhost:8000"
AUTH_TOKEN = "mysecretapitoken123"
